<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Infrastructure.EWS\Infrastructure.EWS.csproj" />
    <ProjectReference Include="..\Shared.EWS\Shared.EWS.csproj" />
    <ProjectReference Include="..\Domain.EWS\Domain.EWS.csproj" />
  </ItemGroup>

</Project>
